export const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS';
export const UPDATE_PRODUCTS = 'UPDATE_PRODUCTS';
export const REQUEST_PRODUCTS_ERROR = 'REQUEST_PRODUCTS_ERROR';

export const REQUEST_PRODUCT = 'REQUEST_PRODUCT';
export const CHOOSE_PRODUCT = 'CHOOSE_PRODUCT';
export const PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND';
