export const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS';
export const UPDATE_PRODUCTS = 'UPDATE_PRODUCTS';
export const REQUEST_PRODUCTS_ERROR = 'REQUEST_PRODUCTS_ERROR';
export const RESET_PRODUCTS = 'RESET_PRODUCTS';

export const REQUEST_PRODUCT = 'REQUEST_PRODUCT';
export const CHOOSE_PRODUCT = 'CHOOSE_PRODUCT';
export const PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND';
export const MODIFY_PRODUCT = 'MODIFY_PRODUCT';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const UPDATE_CART_TOTAL = 'UPDATE_CART_TOTAL';
export const RESET_CART = 'RESET_CART';

export const SEND_ORDER = 'SEND_ORDER';
export const ORDER_RECEIVED = 'ORDER_RECEIVED';
export const ORDER_ERROR = 'ORDER_ERROR';

export const SEARCHBAR_REQUEST_PRODUCTS = 'SEARCHBAR_REQUEST_PRODUCTS';
export const SEARCHBAR_RECEIVED_PRODUCTS = 'SEARCHBAR_RECEIVED_PRODUCTS';
export const SEARCHBAR_ERROR = 'SEARCHBAR_ERROR';
export const RESET_SEARCHBAR = 'RESET_SEARCHBAR';

export const UPDATE_FILTERS = 'UPDATE_FILTERS';
export const RESET_FILTERS = 'RESET_FILTERS';

export const UPDATE_QUERY = 'UPDATE_QUERY';
export const RESET_QUERY = 'RESET_QUERY';
export const INC_PAGINATION = 'INC_PAGINATION';
